on:
  push:
    branches:
    - '**'

jobs:
  test:
    runs-on: windows-11-arm

    steps:
    - name: test
      shell: bash
      run: |
        which curl || true
        which clang || true
        which gcc || true
        which go && go version
        go run a.go
