on:
  push:
    branches:
    - '**'

jobs:
  test:
    runs-on: windows-11-arm

    steps:
    - name: test
      shell: bash
      run: |
        which pacman
        pacman -S mingw-w64-clang-aarch64-clang
